name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: ZIP files
        run: |
          cd /home/runner/work/home-assistant-vacuum-styj02ym/home-assistant-vacuum-styj02ym/custom_components/miio2
          zip miio2.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/home-assistant-vacuum-styj02ym/home-assistant-vacuum-styj02ym/custom_components/miio2/miio2.zip
          asset_name: miio2.zip
          tag: ${{ github.ref }}
          overwrite: true